name: minimal_ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  android: true
  ios: true
  web: false

  android_12:
    color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"
  


  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/
